fullnameOverride: ""
nameOverride: ""

imageRepository: louisleblin/prometheus-switchbot-exporter
imageTag: ""
imagePullPolicy: Always

# This is needed to be able to use the blueooth device
# TODO: investigate options requesting narrower permissions
securityContext:
  privileged: true

metricsPort: 8080

resources:
  limits:
    cpu: 25m
    memory: 32Mi
  requests:
    cpu: 25m
    memory: 32Mi

serviceMonitorOptions:
  interval: 10s
