{
 "title": "SwitchBot Meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(switchbot_battery, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (device) (switchbot_battery{device=\"$device\"})",
     "legendFormat": "{{ $device }}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "description": "Received Signal Strength Indicator.",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "max by (device) (switchbot_rssi{device=\"$device\"})",
     "legendFormat": "{{ $device }}"
    }
   ]
  },
  {
   "title": "Temperate (Celsius)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by (device) (switchbot_temperature{device=\"$device\"})",
     "legendFormat": "{{ $device }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "max by (device) (switchbot_humidity{device=\"$device\"})",
     "legendFormat": "{{ $device }}"
    }
   ]
  }
 ]
}